# Disable spring banner and application name
spring:
  application:
    name: "diff-service"

# Application port and compression properties
server:
  port: 0
  compression:
    enabled: true

# Service registry integration properties
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${random.value}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Increase service communication timeout timeout
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

# Set default request logging
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG